// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotionTaskAutomation.Db;

#nullable disable

namespace NotionTaskAutomation.Migrations
{
    [DbContext(typeof(NotionDbContext))]
    partial class NotionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0-rc.2.24474.1");

            modelBuilder.Entity("NotionTaskAutomation.Db.NotionDbContext+NotionPageRule", b =>
                {
                    b.Property<Guid>("RuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("DayOffset")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EndingState")
                        .HasColumnType("TEXT");

                    b.Property<string>("OnDay")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StartingState")
                        .HasColumnType("TEXT");

                    b.HasKey("RuleId");

                    b.ToTable("NotionPageRules");
                });
#pragma warning restore 612, 618
        }
    }
}
