// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotionAutomation.Db;

#nullable disable

namespace NotionAutomation.Migrations
{
    [DbContext(typeof(NotionDbContext))]
    [Migration("20241101135431_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0-rc.2.24474.1");

            modelBuilder.Entity("NotionAutomation.Objects.NotionDatabaseRule", b =>
                {
                    b.Property<Guid>("RuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DatabaseId")
                        .HasColumnType("TEXT");

                    b.Property<int>("DayOffset")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EndingState")
                        .HasColumnType("TEXT");

                    b.Property<string>("OnDay")
                        .HasColumnType("TEXT");

                    b.Property<string>("StartingState")
                        .HasColumnType("TEXT");

                    b.HasKey("RuleId");

                    b.ToTable("NotionDatabaseRules");
                });
#pragma warning restore 612, 618
        }
    }
}
